import { useMemo, useRef, useState } from 'react';
import Modal from '../Modal';
import { Btn, Input, Select } from '../ui';
import { AttachmentUpload } from '../AttachmentUpload';
import { ISSUE_CAUSE_LEVEL_1, ISSUE_CAUSE_LEVEL_2, ISSUE_CAUSE_LEVEL_3 } from '../../data/issuePool';

function Field({ label, required = false, children }: any) { return <div><label className="mb-1 block text-xs text-gray-600">{label} {required && <span className="text-red-500">*</span>}</label>{children}</div>; }

export function CategorySelect({ label, value, options, onChange }: any) {
  const [open, setOpen] = useState(false);
  const [query, setQuery] = useState('');
  const visible = useMemo(() => options.filter((item) => item.includes(query)), [options, query]);
  const known = !value || options.includes(value);
  return <div className="relative"><label className="mb-1 block text-xs text-gray-600">{label}</label>{value && !known && <p className="mb-1 rounded border border-amber-200 bg-amber-50 px-2 py-1 text-xs text-amber-700">当前值：{value}。现有台账异常值，待业务确认。</p>}<div className="flex gap-1"><button type="button" className="ui-input min-w-0 flex-1 text-left" onClick={() => setOpen((item) => !item)}>{value || '请选择'}</button>{value && <button type="button" className="ui-input w-8 px-0 text-gray-400" onClick={() => onChange('')}>×</button>}</div>{open && <div className="absolute z-20 mt-1 w-full rounded-md border border-gray-200 bg-white p-2 shadow-lg"><Input autoFocus placeholder="搜索已有选项" value={query} onChange={(event) => setQuery(event.target.value)} /><div className="mt-2 max-h-44 overflow-auto divide-y divide-gray-100">{visible.length ? visible.map((item) => <button type="button" key={item} className="block w-full px-2 py-2 text-left text-xs text-gray-700 hover:bg-gray-50" onClick={() => { onChange(item); setOpen(false); setQuery(''); }}>{item}</button>) : <p className="px-2 py-2 text-xs text-gray-400">未找到已有选项。</p>}</div></div>}</div>;
}

function Materials({ form, setForm, disabled = false }) { return <div className="rounded-md border border-gray-200 p-3 space-y-3"><p className="text-xs font-medium text-gray-700">详情上传（图片&视频&log）</p><p className="text-xs text-gray-400">资料记录（暂不上传真实文件）</p><AttachmentUpload disabled={disabled} value={form.materialName} onChange={(materialName) => setForm((prev) => ({ ...prev, materialName }))} label="附件" /><div className="grid grid-cols-1 gap-2 sm:grid-cols-2"><Input disabled={disabled} placeholder="资料用途" value={form.materialPurpose} onChange={(event) => setForm((prev) => ({ ...prev, materialPurpose: event.target.value }))} /><Input disabled={disabled} placeholder="资料备注（选填）" value={form.materialNote} onChange={(event) => setForm((prev) => ({ ...prev, materialNote: event.target.value }))} /></div></div>; }

export default function IssueRecordModal({ isOpen, onClose, onSave, mode = 'manual', defaults = {}, devices = [], projects = [], currentUser = '', title, submitLabel }: any) {
  const delivery = mode === 'delivery';
  const [form, setForm] = useState({ customerName: '', causeLevel1: '', causeLevel2: '', causeLevel3: '', symptom: '', siteTroubleshooting: '', temporarySolution: '', reporter: currentUser || '', deviceIdentifier: '', reportedAt: '', projectName: '', softwareVersion: '', deviceId: '', materialName: '', materialPurpose: '问题资料', materialNote: '', ...defaults });
  const [query, setQuery] = useState('');
  const [devicePickerOpen, setDevicePickerOpen] = useState(false);
  const [error, setError] = useState('');
  const [submitting, setSubmitting] = useState(false);
  const guard = useRef(false);
  const deliveryDevice = delivery ? devices[0] : null;
  const matches = devices.filter((item) => !query || `${item.sn} ${item.robotNo}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8);
  const setValue = (key, value) => { setForm((prev) => ({ ...prev, [key]: value })); setError(''); };
  const selectDevice = (device) => { const project = projects.find((item) => item.id === device.projectId); setForm((prev) => ({ ...prev, deviceId: device.id, deviceIdentifier: device.sn || device.robotNo || prev.deviceIdentifier, projectName: project?.name || prev.projectName, projectId: project?.id || prev.projectId, customerName: project?.client || prev.customerName, softwareVersion: device.softwareVersion || prev.softwareVersion })); setQuery(''); setDevicePickerOpen(false); };
  const clearDevice = () => { setForm((prev) => ({ ...prev, deviceId: '' })); setQuery(''); setDevicePickerOpen(false); };
  const submit = async () => { if (guard.current) return; if (!form.symptom.trim()) return setError('请填写故障现象描述。'); if (!form.reporter.trim()) return setError('请填写提报人。'); if (!form.reportedAt) return setError('请填写提报时间。'); guard.current = true; setSubmitting(true); try { await Promise.resolve(onSave(form)); } catch (reason) { guard.current = false; setSubmitting(false); setError(reason instanceof Error ? reason.message : '保存问题失败，请重试。'); } };
  const locked = delivery;
  return <Modal size="2xl" isOpen={isOpen} onClose={submitting ? () => {} : onClose} title={title || (delivery ? '提交设备问题至问题池' : '人工新建问题')}><div className="space-y-5 pb-14"><div className="rounded-md border border-gray-200 bg-gray-50 px-3 py-2 text-xs text-gray-600">{delivery ? <><p>当前设备已自动关联，提交后将在问题池中持续跟进。</p><div className="mt-2 grid grid-cols-2 gap-x-4 gap-y-1 text-gray-500 sm:grid-cols-4"><span>机器人编号：{deliveryDevice?.robotNo || '—'}</span><span>设备 SN：{deliveryDevice?.sn || '—'}</span><span>设备型号：{deliveryDevice?.model || '—'}</span><span>当前项目：{form.projectName || '—'}</span></div></> : '填写已知问题信息；可通过设备搜索关联已有设备。'}</div>
    <section className="space-y-3"><h3 className="text-[13px] font-semibold text-gray-800">基础信息</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="问题编号"><Input disabled value="保存后由系统生成" /></Field><Field label="客户名称"><Input disabled={locked} value={form.customerName} onChange={(event) => setValue('customerName', event.target.value)} /></Field><Field label="项目"><Select disabled={locked} value={form.projectName} onChange={(event) => { const project = projects.find((item) => item.name === event.target.value); setForm((prev) => ({ ...prev, projectName: event.target.value, projectId: project?.id || prev.projectId, customerName: project?.client || prev.customerName })); }}><option value="">请选择或留空</option>{projects.map((item) => <option key={item.id}>{item.name}</option>)}</Select></Field><Field label="机器人 SN 编号 or 设备 WIFI 名称"><Input disabled={locked} value={form.deviceIdentifier} onChange={(event) => setValue('deviceIdentifier', event.target.value)} /></Field><Field label="软件版本号"><Input disabled={locked} value={form.softwareVersion} onChange={(event) => setValue('softwareVersion', event.target.value)} /></Field><Field label="提报人" required><Input disabled={locked} value={form.reporter} onChange={(event) => setValue('reporter', event.target.value)} /></Field><Field label="提报时间" required><Input disabled={locked} type="datetime-local" value={form.reportedAt} onChange={(event) => setValue('reportedAt', event.target.value)} /></Field></div>{!delivery && <div className="rounded-md border border-gray-200 p-3 space-y-2"><div className="flex items-center justify-between gap-2"><p className="text-xs font-medium text-gray-700">设备档案辅助匹配</p>{form.deviceId && <button type="button" className="ui-link text-xs" onClick={clearDevice}>清除已关联设备</button>}</div>{form.deviceId && <p className="rounded border border-emerald-200 bg-emerald-50 px-2 py-1.5 text-xs text-emerald-700">已关联设备：{devices.find((item) => item.id === form.deviceId)?.robotNo || '—'} / {devices.find((item) => item.id === form.deviceId)?.sn || form.deviceIdentifier}</p>}<Input placeholder="搜索设备 SN / 机器人编号" value={query} onFocus={() => setDevicePickerOpen(true)} onChange={(event) => { setQuery(event.target.value); setDevicePickerOpen(true); }} />{devicePickerOpen && <div className="max-h-48 divide-y divide-gray-100 overflow-auto rounded-md border border-gray-100">{matches.length ? matches.map((device) => <button type="button" key={device.id} className={`block w-full px-3 py-2 text-left text-xs hover:bg-gray-50 ${form.deviceId === device.id ? 'bg-emerald-50 text-emerald-800' : ''}`} onMouseDown={(event) => event.preventDefault()} onClick={() => selectDevice(device)}>{device.sn} · {device.robotNo}</button>) : <p className="px-3 py-2 text-xs text-gray-400">未匹配到设备，仍可保留原始填写值。</p>}</div>}</div>}</section>
    <section className="space-y-3 border-t border-gray-100 pt-4"><h3 className="text-[13px] font-semibold text-gray-800">问题描述</h3><Field label="故障现象描述" required><textarea className="ui-input min-h-20 w-full" value={form.symptom} onChange={(event) => setValue('symptom', event.target.value)} /></Field><div className="grid grid-cols-1 gap-3 sm:grid-cols-2"><Field label="已做排查动作"><textarea className="ui-input min-h-20 w-full" value={form.siteTroubleshooting} onChange={(event) => setValue('siteTroubleshooting', event.target.value)} /></Field><Field label="临时解决方案"><textarea className="ui-input min-h-20 w-full" value={form.temporarySolution} onChange={(event) => setValue('temporarySolution', event.target.value)} /></Field></div><Materials form={form} setForm={setForm} /></section>
    <section className="space-y-3 border-t border-gray-100 pt-4"><h3 className="text-[13px] font-semibold text-gray-800">故障分类</h3><div className="grid grid-cols-1 gap-3 sm:grid-cols-3"><CategorySelect label="一级故障原因分类" value={form.causeLevel1} options={ISSUE_CAUSE_LEVEL_1} onChange={(value) => setValue('causeLevel1', value)} /><CategorySelect label="二级故障原因分类" value={form.causeLevel2} options={ISSUE_CAUSE_LEVEL_2} onChange={(value) => setValue('causeLevel2', value)} /><CategorySelect label="三级故障分类" value={form.causeLevel3} options={ISSUE_CAUSE_LEVEL_3} onChange={(value) => setValue('causeLevel3', value)} /></div></section>
    {error && <p className="text-xs text-red-600">{error}</p>}<div className="sticky bottom-0 -mx-5 flex items-center justify-between gap-3 border-t border-gray-100 bg-white px-5 py-3"><p className="text-xs text-gray-400">{delivery ? '提交后返回当前设备并展示正式问题编号。' : '保存后进入问题详情。'}</p><div className="flex gap-2"><Btn disabled={submitting} onClick={onClose}>取消</Btn><Btn variant="primary" disabled={submitting} onClick={submit}>{submitting ? '保存中…' : submitLabel || (delivery ? '提交至问题池' : '保存问题')}</Btn></div></div>
  </div></Modal>;
}
