import { useMemo, useState } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { useApp } from '../context/AppContext';
import { Btn, DescList, Input, Page, PageHeader, Section, Select, Stepper, Table } from '../components/ui';
import Modal from '../components/Modal';
import StatusBadge from '../components/StatusBadge';
import { afterSalesCloseReasons, afterSalesGuidance, type AfterSalesOrder } from '../data/afterSalesOrders';
import { createClientId } from '../data/clientId';
import { nowText } from '../data/dateTime';

const STEPS = ['待分派', '待接单', '待上门', '现场处理中', '已关单'].map((label) => ({ label }));
const dash = (value?: string) => value || '—';
const dateValue = () => nowText().replace(' ', 'T');

export default function AfterSalesOrderDetail() {
  const { orderId } = useParams();
  const navigate = useNavigate();
  const { state, dispatch } = useApp();
  const [modal, setModal] = useState<string | null>(null);
  const [message, setMessage] = useState('');
  const order = state.afterSalesOrders.find((item) => item.id === orderId) as AfterSalesOrder | undefined;
  const issue = order ? state.issueRecords.find((item) => item.id === order.issueId) : undefined;
  const engineers = useMemo(() => [...new Set([state.currentUser, ...(state.users || []).map((item) => item.name || item)].filter(Boolean))], [state.currentUser, state.users]);

  if (!order) return <Page><PageHeader title="售后工单不存在" /><Btn as="link" to="/after-sales?tab=orders">返回售后工单</Btn></Page>;
  const readOnly = order.status === '已关单' || order.status === '已取消';
  const guidance = afterSalesGuidance(order);
  const update = (patch: Partial<AfterSalesOrder>, action: string, notes: string) => {
    const time = nowText();
    dispatch({ type: 'UPDATE_AFTER_SALES_ORDER', payload: { ...order, ...patch, updatedAt: time, logs: [...order.logs, { id: createClientId('ASOLOG'), time, operator: state.currentUser || '当前用户', action, notes }] } });
    setModal(null);
    setMessage('');
  };
  const primary = () => {
    if (guidance.action === 'accept') return update({ status: '待上门', acceptedAt: nowText() }, '确认接单', '工单状态：待接单 → 待上门');
    if (guidance.action === 'assign') return setModal('assign');
    if (guidance.action === 'plan-visit') return setModal('plan');
    if (guidance.action === 'arrive') return setModal('arrive');
    if (guidance.action === 'handle') return setModal('handle');
    if (guidance.action === 'close') return setModal('close');
  };

  return <Page>
    <PageHeader title={order.orderNo} description="售后现场执行记录仅来自正式问题池记录。" breadcrumb={<div className="mb-1 text-xs text-gray-400"><Link className="ui-link" to="/after-sales?tab=orders">售后工单</Link> / {order.orderNo}</div>} actions={<Btn as="link" to="/after-sales?tab=orders">返回售后工单</Btn>} />
    {message && <div className="rounded-md border border-amber-200 bg-amber-50 px-3 py-2 text-xs text-amber-800">{message}</div>}
    <Section title="当前待办" subtitle="按当前阶段完成一个主要操作；来源问题与售后执行状态分别维护。" right={!readOnly && guidance.action !== 'none' ? <Btn variant="primary" onClick={primary}>{guidance.label}</Btn> : <StatusBadge status={order.status} />}>
      <div className="grid gap-4 lg:grid-cols-[1.2fr_1fr]"><Stepper steps={STEPS} current={order.status === '已取消' ? 0 : order.status} /><div className="space-y-2 text-[13px]"><div><span className="text-gray-400">当前待办：</span><b className="text-gray-800">{guidance.task}</b></div><div><span className="text-gray-400">尚未满足：</span>{guidance.unmet.length ? guidance.unmet.join('、') : '—'}</div><div><span className="text-gray-400">下一阶段：</span>{guidance.next || '—'}</div><div><span className="text-gray-400">当前售后工程师：</span>{dash(order.engineer)}</div></div></div>
      {!readOnly && (order.status === '待分派' || order.status === '待接单') && <div className="mt-4 border-t border-gray-100 pt-3"><Btn size="sm" variant="danger" onClick={() => setModal('cancel')}>取消工单</Btn></div>}
    </Section>
    <Section title="来源问题快照" subtitle="创建售后工单时保存，不会被后续问题编辑无痕覆盖。" right={<Btn size="sm" as="link" to={`/after-sales?issue=${order.issueId}`}>查看最新问题记录</Btn>}>
      <DescList cols={3} items={[["问题编号", <Link className="ui-link font-mono text-xs" to={`/after-sales?issue=${order.issueId}`}>{order.issueNo}</Link>], ['客户名称', dash(order.snapshot.customerName)], ['项目', dash(order.snapshot.projectName)], ['设备标识', order.deviceId ? <Link className="ui-link font-mono text-xs" to={`/devices/${order.deviceId}?tab=project`}>{dash(order.snapshot.deviceIdentifier)}</Link> : dash(order.snapshot.deviceIdentifier)], ['来源交付任务', order.sourceSubOrderId && order.deliveryPlanId ? <Link className="ui-link text-xs" to={`/delivery-plans/${order.deliveryPlanId}/sub-orders/${order.sourceSubOrderId}`}>查看来源交付任务</Link> : '—'], ['故障现象描述', dash(order.snapshot.symptom)], ['一级故障原因分类', dash(order.snapshot.causeLevel1)], ['二级故障原因分类', dash(order.snapshot.causeLevel2)], ['三级故障分类', dash(order.snapshot.causeLevel3)], ['根因分析', dash(order.snapshot.rootCause)], ['长期问题解决方案', dash(order.snapshot.longTermSolution)], ['技术客服处理判断', dash(order.snapshot.technicalSupport?.decision)], ['判断说明', dash(order.snapshot.technicalSupport?.note)], ['判断人', dash(order.snapshot.technicalSupport?.handler)], ['判断时间', dash(order.snapshot.technicalSupport?.handledAt)], ['来源资料', order.snapshot.attachments.length ? order.snapshot.attachments.map((item) => item.name).join('、') : '—']]} />
    </Section>
    <Section title="分派与上门安排">
      <DescList cols={3} items={[["分派人", dash(order.assignedBy)], ['售后工程师', dash(order.engineer)], ['分派时间', dash(order.assignedAt)], ['接单时间', dash(order.acceptedAt)], ['预计上门时间', dash(order.plannedVisitAt)], ['实际上门时间', dash(order.actualVisitAt)], ['上门说明', dash(order.visitNote)]]} />
    </Section>
    <Section title="现场处理" subtitle="现场工程师填写的实际处理事实，不覆盖来源问题快照。" right={!readOnly && order.status === '现场处理中' ? <div className="flex gap-2"><Btn size="sm" onClick={() => setModal('material')}>补充资料</Btn><Btn size="sm" onClick={() => setModal('handle')}>记录现场处理</Btn></div> : undefined}>
      <DescList cols={2} items={[["现场处理说明", dash(order.onsiteHandling)], ['实际故障原因', dash(order.actualCause)], ['实际处理方案', dash(order.actualSolution)], ['最终处理结果', dash(order.finalResult)], ['是否涉及换件', order.involvesReplacement ? '是，换件记录待后续接入' : '否']]} />
      <div className="mt-4 border-t border-gray-100 pt-3"><p className="mb-2 text-xs text-gray-400">现场资料（暂不上传真实文件）</p>{order.materials.length ? <ul className="space-y-1 text-[13px] text-gray-700">{order.materials.map((item) => <li key={item.id}>• {item.name} <span className="text-gray-400">/ {item.purpose} / {item.addedBy} / {item.addedAt}</span></li>)}</ul> : <p className="text-[13px] text-gray-400">暂无现场资料。</p>}</div>
    </Section>
    <Section title="关单信息"><DescList cols={3} items={[["关单人", dash(order.closedBy)], ['关单时间', dash(order.closedAt)], ['关单说明', dash(order.closeNote)], ['关联问题处理结果', order.issueOutcome === 'resolved' ? '问题已解决并闭环' : order.issueOutcome === 'observe' ? '现场处理完成，仍需观察' : '—'], ['取消人', dash(order.cancelledBy)], ['取消时间', dash(order.cancelledAt)], ['取消原因', dash(order.cancelReason)]]} /></Section>
    <Section title={`操作日志（${order.logs.length}）`} bodyClassName="p-0"><Table head={['时间', '操作人', '操作内容', '说明']} empty="暂无售后操作日志">{order.logs.slice().reverse().map((log) => <tr key={log.id}><td className="px-3 py-2 text-xs text-gray-500">{log.time}</td><td className="px-3 py-2">{log.operator}</td><td className="px-3 py-2">{log.action}</td><td className="px-3 py-2 text-xs text-gray-600">{log.notes}</td></tr>)}</Table></Section>
    <AssignModal isOpen={modal === 'assign'} engineers={engineers} onClose={() => setModal(null)} onSave={(engineer) => update({ status: '待接单', engineer, assignedBy: state.currentUser || '当前用户', assignedAt: nowText() }, '分派售后工程师', `售后工程师：未分派 → ${engineer}；工单状态：待分派 → 待接单`)} />
    <PlanModal isOpen={modal === 'plan'} onClose={() => setModal(null)} onSave={(plannedVisitAt, visitNote) => update({ plannedVisitAt: plannedVisitAt.replace('T', ' '), visitNote }, '设置预计上门时间', `预计上门时间：— → ${plannedVisitAt.replace('T', ' ')}`)} />
    <ArriveModal isOpen={modal === 'arrive'} onClose={() => setModal(null)} onSave={(actualVisitAt, visitNote) => update({ status: '现场处理中', actualVisitAt: actualVisitAt.replace('T', ' '), visitNote: visitNote || order.visitNote }, '确认已到现场', `工单状态：待上门 → 现场处理中；实际上门时间：${actualVisitAt.replace('T', ' ')}`)} />
    <HandleModal isOpen={modal === 'handle'} order={order} onClose={() => setModal(null)} onSave={(values) => update(values, '记录现场处理', '已更新现场处理说明、实际处理方案和最终处理结果')} />
    <MaterialModal isOpen={modal === 'material'} onClose={() => setModal(null)} onSave={(material) => update({ materials: [...order.materials, material] }, '补充现场资料', `已添加现场资料：${material.name}`)} />
    <CloseModal isOpen={modal === 'close'} order={order} onClose={() => setModal(null)} onSave={(closeNote, material, issueOutcome) => { const materials = material ? [...order.materials, material] : order.materials; const missing = afterSalesCloseReasons({ ...order, closeNote, materials }); if (missing.length) return setMessage(`暂不能关单，缺少：${missing.join('、')}。`); const closedAt = nowText(); update({ status: '已关单', closeNote, closedBy: state.currentUser || '当前用户', closedAt, materials, issueOutcome }, '完成并关单', `工单状态：现场处理中 → 已关单；关联问题处理结果：${issueOutcome === 'resolved' ? '已解决并闭环' : '现场处理完成，仍需观察'}`); if (issue) { const nextStatus = issueOutcome === 'resolved' ? '已完成' : '观察导入措施是否有效'; const nextClosed = issueOutcome === 'resolved' ? '是' : '否'; dispatch({ type: 'UPDATE_ISSUE_RECORD', payload: { ...issue, resolutionStatus: nextStatus, isClosed: nextClosed, activityLogs: [...(issue.activityLogs || []), { id: createClientId('ISSUELOG'), time: closedAt, operator: state.currentUser || '当前用户', action: '售后关单同步问题处理结果', notes: `来源售后工单 ${order.orderNo} 已关单；解决状态：${issue.resolutionStatus || '—'} → ${nextStatus}；问题是否闭环：${issue.isClosed || '—'} → ${nextClosed}` }] } }); } }} />
    <CancelModal isOpen={modal === 'cancel'} onClose={() => setModal(null)} onSave={(reason) => update({ status: '已取消', cancelledBy: state.currentUser || '当前用户', cancelledAt: nowText(), cancelReason: reason }, '取消售后工单', `工单状态：${order.status} → 已取消；取消原因：${reason}`)} />
  </Page>;
}

function FormModal({ isOpen, onClose, title, children }: any) { return <Modal isOpen={isOpen} onClose={onClose} title={title}><div className="space-y-4">{children}</div></Modal>; }
function Field({ label, required, children }: any) { return <label className="block space-y-1"><span className="text-xs text-gray-600">{label}{required && <b className="ml-1 text-red-500">*</b>}</span>{children}</label>; }
function Textarea(props: any) { return <textarea {...props} className="ui-input min-h-20 resize-y" />; }

function AssignModal({ isOpen, onClose, onSave, engineers }: any) { const [engineer, setEngineer] = useState(''); return <FormModal isOpen={isOpen} onClose={onClose} title="分派售后工程师"><p className="text-xs text-gray-500">分派后工单将进入“待接单”，由售后工程师确认接单。</p><Field label="售后工程师" required><Select value={engineer} onChange={(event) => setEngineer(event.target.value)}><option value="">请选择售后工程师</option>{engineers.map((item) => <option key={item}>{item}</option>)}</Select></Field><div className="flex justify-end gap-2"><Btn onClick={onClose}>取消</Btn><Btn variant="primary" disabled={!engineer} onClick={() => onSave(engineer)}>确认分派</Btn></div></FormModal>; }
function PlanModal({ isOpen, onClose, onSave }: any) { const [planned, setPlanned] = useState(''); const [note, setNote] = useState(''); return <FormModal isOpen={isOpen} onClose={onClose} title="设置预计上门时间"><p className="text-xs text-gray-500">保存后工单仍处于“待上门”，可在工程师到场后确认实际上门时间。</p><Field label="预计上门时间" required><Input type="datetime-local" value={planned} onChange={(event) => setPlanned(event.target.value)} /></Field><Field label="上门说明"><Textarea value={note} onChange={(event) => setNote(event.target.value)} /></Field><div className="flex justify-end gap-2"><Btn onClick={onClose}>取消</Btn><Btn variant="primary" disabled={!planned} onClick={() => onSave(planned, note)}>保存上门安排</Btn></div></FormModal>; }
function ArriveModal({ isOpen, onClose, onSave }: any) { const [actual, setActual] = useState(dateValue()); const [note, setNote] = useState(''); return <FormModal isOpen={isOpen} onClose={onClose} title="确认已到现场"><p className="text-xs text-gray-500">确认后工单进入“现场处理中”，可以记录实际处理过程和资料。</p><Field label="实际上门时间" required><Input type="datetime-local" value={actual} onChange={(event) => setActual(event.target.value)} /></Field><Field label="上门说明"><Textarea value={note} onChange={(event) => setNote(event.target.value)} /></Field><div className="flex justify-end gap-2"><Btn onClick={onClose}>取消</Btn><Btn variant="primary" disabled={!actual} onClick={() => onSave(actual, note)}>确认已到现场</Btn></div></FormModal>; }
function HandleModal({ isOpen, onClose, onSave, order }: any) { const [values, setValues] = useState({ onsiteHandling: order?.onsiteHandling || '', actualCause: order?.actualCause || '', actualSolution: order?.actualSolution || '', finalResult: order?.finalResult || '', involvesReplacement: Boolean(order?.involvesReplacement) }); const set = (key, value) => setValues((prev) => ({ ...prev, [key]: value })); return <FormModal isOpen={isOpen} onClose={onClose} title="记录现场处理"><p className="text-xs text-gray-500">保存后更新本售后工单的现场处理事实，不修改来源问题记录。</p><Field label="现场处理说明" required><Textarea value={values.onsiteHandling} onChange={(event) => set('onsiteHandling', event.target.value)} /></Field><Field label="实际故障原因"><Textarea value={values.actualCause} onChange={(event) => set('actualCause', event.target.value)} /></Field><Field label="实际处理方案" required><Textarea value={values.actualSolution} onChange={(event) => set('actualSolution', event.target.value)} /></Field><Field label="最终处理结果" required><Textarea value={values.finalResult} onChange={(event) => set('finalResult', event.target.value)} /></Field><label className="flex items-center gap-2 text-sm text-gray-700"><input type="checkbox" checked={values.involvesReplacement} onChange={(event) => set('involvesReplacement', event.target.checked)} />涉及换件 <span className="text-xs text-gray-400">换件记录待后续接入</span></label><div className="flex justify-end gap-2"><Btn onClick={onClose}>取消</Btn><Btn variant="primary" disabled={!values.onsiteHandling.trim() || !values.actualSolution.trim() || !values.finalResult.trim()} onClick={() => onSave(values)}>保存现场处理</Btn></div></FormModal>; }
function MaterialModal({ isOpen, onClose, onSave }: any) { const [name, setName] = useState(''); const [purpose, setPurpose] = useState('处理结果证明'); const [note, setNote] = useState(''); return <FormModal isOpen={isOpen} onClose={onClose} title="补充现场资料"><p className="text-xs text-gray-500">资料记录（暂不上传真实文件）。</p><Field label="文件名" required><Input value={name} onChange={(event) => setName(event.target.value)} /></Field><Field label="资料用途" required><Input value={purpose} onChange={(event) => setPurpose(event.target.value)} /></Field><Field label="备注"><Textarea value={note} onChange={(event) => setNote(event.target.value)} /></Field><div className="flex justify-end gap-2"><Btn onClick={onClose}>取消</Btn><Btn variant="primary" disabled={!name.trim() || !purpose.trim()} onClick={() => onSave({ id: createClientId('ASOMAT'), name: name.trim(), purpose: purpose.trim(), addedBy: '当前用户', addedAt: nowText(), note: note.trim() })}>保存资料记录</Btn></div></FormModal>; }
function CloseModal({ isOpen, onClose, onSave, order }: any) { const [note, setNote] = useState(''); const [proof, setProof] = useState(''); const [outcome, setOutcome] = useState<'resolved' | 'observe' | ''>(''); const [error, setError] = useState(''); const material = proof.trim() ? { id: createClientId('ASOMAT'), name: proof.trim(), purpose: '正常工作视频或处理结果证明', addedBy: '当前用户', addedAt: nowText() } : undefined; const missing = afterSalesCloseReasons({ ...order, closeNote: note, materials: material ? [...order.materials, material] : order.materials }); return <FormModal isOpen={isOpen} onClose={onClose} title="完成并关单"><p className="text-xs text-gray-500">关单后工单只读；本次需同步维护来源问题的既有“解决状态”和“问题是否闭环”字段，不修改当前交付结果。</p><Field label="关单说明" required><Textarea value={note} onChange={(event) => { setNote(event.target.value); setError(''); }} /></Field><Field label="正常工作视频或处理结果证明资料" required><Input value={proof} onChange={(event) => { setProof(event.target.value); setError(''); }} placeholder="填写资料文件名" /></Field><div className="space-y-2"><p className="text-xs text-gray-600">关联问题处理结果 <b className="text-red-500">*</b></p><label className="flex gap-2 text-[13px]"><input type="radio" checked={outcome === 'resolved'} onChange={() => setOutcome('resolved')} />问题已解决并闭环</label><label className="flex gap-2 text-[13px]"><input type="radio" checked={outcome === 'observe'} onChange={() => setOutcome('observe')} />现场处理完成，仍需观察</label></div>{error && <p className="text-xs text-red-600">{error}</p>}{missing.length > 0 && <p className="rounded-md bg-amber-50 px-3 py-2 text-xs text-amber-800">尚未满足：{missing.join('、')}</p>}<div className="flex justify-end gap-2"><Btn onClick={onClose}>取消</Btn><Btn variant="primary" disabled={missing.length > 0 || !outcome} onClick={() => { if (!outcome) return setError('请选择关联问题处理结果。'); onSave(note, material, outcome); }}>确认完成并关单</Btn></div></FormModal>; }
function CancelModal({ isOpen, onClose, onSave }: any) { const [reason, setReason] = useState(''); return <FormModal isOpen={isOpen} onClose={onClose} title="取消售后工单"><p className="text-xs text-gray-500">取消后工单只读，不会自动关闭或闭环来源问题。</p><Field label="取消原因" required><Textarea value={reason} onChange={(event) => setReason(event.target.value)} /></Field><div className="flex justify-end gap-2"><Btn onClick={onClose}>返回</Btn><Btn variant="danger" disabled={!reason.trim()} onClick={() => onSave(reason.trim())}>确认取消工单</Btn></div></FormModal>; }
